siteName: БПЛР–БАНКЯ
siteDescription: >-
  Болница за продължително лечение и рехабилитация – Банкя. Рехабилитация с
  природна минерална вода, физиотерапия и специализирани медицински грижи.
footerDescription: >-
  Специализирана болница за рехабилитация в Банкя, предлагаща комплексно лечение
  с природни минерални води и съвременни методи.
phone: 02 997 7194
email: bbbankya@abv.bg
address: гр. Банкя, ул. Цар Симеон № 2, 1320
hours: 'Пон – Пет: 08:00 – 18:00'
mapsEmbedUrl: >-
  <iframe
  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2932.0259302444683!2d23.142202676610175!3d42.70317171335504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa990c07e99101%3A0xf317d96000c2c69e!2z0JHQvtC70L3QuNGG0LAg0LfQsCDQv9GA0L7QtNGK0LvQttC40YLQtdC70L3QviDQu9C10YfQtdC90LjQtSDQuCDRgNC10YXQsNCx0LjQu9C40YLQsNGG0LjRjyDQktCc0JAgLSDQkdCw0L3QutGP!5e0!3m2!1sbg!2sbg!4v1776100549339!5m2!1sbg!2sbg"
  width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
  referrerpolicy="no-referrer-when-downgrade"></iframe>
facebookUrl: https://www.facebook.com
